name: ⏱ Mark Inactive Users

on:
  schedule:
    - cron: '*/15 * * * *'  # 每15分钟触发一次
  workflow_dispatch:        # 允许手动触发

jobs:
  clean-inactive-users:
    runs-on: ubuntu-latest

    steps:
    - name: ✅ Checkout repo
      uses: actions/checkout@v3

    - name: ✅ Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: ✅ Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: ✅ Run cleanup script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
      run: |
        python -c "from app import mark_inactive_users; mark_inactive_users()"